title:Bernard Adjei Buckman
description:Jekyll Blog for Bernard A. Buckman

url: http://babuckman.github.io/
baseurl: "http://babuckman.github.io/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

 - title: Contact
   url: /contact

social:
   github: BABuckman
   twitter: babuckman
   facebook: Bernard Buckman [https://www.facebook.com/bernard.buckman]
   email: lordgiver@gmail.com

google_analytics: <!--"UA-58263416-1"-->
